### ISSUE TITLE
One-line .seen response

### ISSUE THREAD

**Issue by anshin** [6c37/deskbot#22]
The current .seen response looks like this:
```
NICK was last seen parting CHAN.
Time: Dec 31 08:34:15 1990. (GMT-3:00)
```

Specificity isn't necessarily beneficial here. I (also, probably most people) want *relative* information from `.seen`, and I (we) have to do mental math to determine how much time has passed. The relative time doesn't necessarily need specificity either, so it might be preferable to not show things like seconds or minutes. Also, taking up two lines is unnecessary.

I suggest one of the following:

`NICK was last seen parting CHAN on Dec 31, 1990`
`NICK was last seen parting CHAN 4 months, 12 days ago`
`NICK was last seen parting CHAN 4 months ago`

**Comment by skewerr** [comment]
bixxx asked me for relative time on the `.seen` response before. I believe I had changed it but had other edits to do and just checkout'd everything. I'll add that in soon.

As for the two lines response, it's done purely for aesthetics. If it's annoying, I'll go for a short option. I'll go with

    NICK was last seen parting CHAN 4 months, 12 days ago.
    NICK was last seen parting CHAN 12 days ago.
    NICK was last seen parting CHAN 20 hours ago.

combined. Thanks, anshin.

**Comment by skewerr** [comment]
With the exception of month counting, deskbot now only replies in one line, when possible(PRIVMSG messages can get pretty long, the bot will split the line in two in that case.).
