### ISSUE TITLE
Address privacy issues with .seen

### ISSUE THREAD

**Issue by anshin** [6c37/deskbot#23]
`.seen` sometimes tells us that someone was last seen speaking in a different channel. This is obviously valuable information to the person who used the command, but it's not ideal for the person on whom the command is run. I may have the `p` mode set (hides non-common channels), I may be in a channel with the `p` and/or `i` modes, but, more importantly, I may just not like the idea of being opted into having my channels revealed as a default.

The only good choice is to default to being private, so isolating `.seen` to the current channel is the best solution I have right now.

**Comment by skewerr** [comment]
Currently, `.untrack` and `.track` can be used by halfop's and up to prevent their channels from being tracked by deskbot. The commands themselves aren't tracked, as the monitor function that stores messages will be ran only after commands are parsed, so the activity in that channel just won't be stored anymore. The channels are tracked by default.

I understand it's annoying and I'll try to find time and motivation to implement mode checking should +p/+i be there the bot will stop tracking activity. For now, please use `.untrack`.

**Comment by skewerr** [comment]
`.seen` has been remade to address these. It currently only works on a per-channel basis.
